name: CI/CD

on:
  # Triggers the workflow on push to main and for pull requests
  push:
    branches: [ main ]
  pull_request:

env:
  PROJECT_NAME: error-sync-lib

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint + Unit Test + Build
        run: |
          cat <<EOT >> commands.txt
          yarn lint
          yarn build
          yarn test
          EOT
          parallel --halt now,fail=1 < commands.txt
